// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7he0l9u0G9pFuzr2e7InRqg_lzoQJOxk',
    appId: '1:461253628285:android:cf9616fe28568d2ce6fc14',
    messagingSenderId: '461253628285',
    projectId: 'animalyard-da031',
    databaseURL: 'https://animalyard-da031-default-rtdb.firebaseio.com',
    storageBucket: 'animalyard-da031.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6rFeNi8E-xIKXe2oudzKGLeHv5zvBqrs',
    appId: '1:461253628285:ios:f0ec5e1798d1d018e6fc14',
    messagingSenderId: '461253628285',
    projectId: 'animalyard-da031',
    databaseURL: 'https://animalyard-da031-default-rtdb.firebaseio.com',
    storageBucket: 'animalyard-da031.appspot.com',
    iosBundleId: 'com.activeitzone.activeecommerceflutterapp',
  );
}
